### ISSUE TITLE
Crashes 1.18.2 Server - Hard Dependency for 1.18.1

### ISSUE THREAD

**Issue by RenegadeT1tan** [PixelAgent007/gottagofast-fabric#1]
HARD_DEP_INCOMPATIBLE_PRESELECTED gottagofast 1.0.1 {depends minecraft @ [1.18.1]}, ROOT_FORCELOAD_SINGLE gottagofast 1.0.1
[latest.log](https://github.com/PixelAgent007/gottagofast-fabric/files/8618516/latest.log)

Would love to see this working in 1.18.2

**Comment by PixelAgent007** [comment]
Ok, thank you. I updated the curseforge, but it'll take awhile for the 1.18.2 version to show up, so I will add a release here on GitHub.
